import { type ReactNode, useEffect } from 'react';
import { useAuth, useClerk, useUser } from '@clerk/react';
import { useQueryClient } from '@tanstack/react-query';
import { CalendarDays, CircleAlert, Clock3, LogOut, UserRound } from 'lucide-react';
import { getGetMyAppointmentsQueryKey, getGetMyProfileQueryKey, useGetMyAppointments, useGetMyProfile } from '@workspace/api-client-react';
import { Link, useLocation } from 'wouter';

function DashboardState({ title, text, action }: { title: string; text: string; action?: ReactNode }) {
  return <div className="rounded-[26px] border border-[hsl(var(--border))] bg-[hsl(var(--card)/.72)] p-8 text-center" data-testid="dashboard-state"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><CircleAlert size={24} /></div><h2 className="serif mt-5 text-2xl text-[hsl(var(--primary))]">{title}</h2><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-[hsl(var(--muted-foreground))]">{text}</p>{action && <div className="mt-6">{action}</div>}</div>;
}

export default function Dashboard() {
  const { isLoaded, isSignedIn } = useAuth();
  const { user } = useUser();
  const { signOut } = useClerk();
  const [, setLocation] = useLocation();
  const queryClient = useQueryClient();
  const profileQuery = useGetMyProfile({ query: { enabled: isLoaded && !!isSignedIn, queryKey: getGetMyProfileQueryKey() } });
  const appointmentsQuery = useGetMyAppointments({ query: { enabled: isLoaded && !!isSignedIn, queryKey: getGetMyAppointmentsQueryKey() } });
  useEffect(() => {
    if (isLoaded && !isSignedIn) setLocation('/sign-in?redirect_url=/dashboard');
    if (profileQuery.data?.role === 'admin') {
      setLocation('/admin');
    } else if (profileQuery.data?.onboardingStatus !== 'complete') {
      if (profileQuery.data) setLocation('/onboarding');
    } else if (profileQuery.data.role === 'staff' || profileQuery.data.accountType === 'staff' || profileQuery.data.accountType === 'admin') {
      setLocation('/staff');
    }
  }, [isLoaded, isSignedIn, profileQuery.data, setLocation]);
  if (!isLoaded || profileQuery.isLoading || appointmentsQuery.isLoading) return <div className="min-h-[100dvh] bg-[hsl(var(--background))]"><div className="page-wrap space-y-4 py-16"><div className="h-8 w-1/3 animate-pulse rounded bg-[hsl(var(--muted))]" /><div className="h-36 animate-pulse rounded-[28px] bg-[hsl(var(--muted))]" /><div className="h-52 animate-pulse rounded-[28px] bg-[hsl(var(--muted))]" /></div></div>;
  if (!isSignedIn) return null;
  if (profileQuery.error || appointmentsQuery.error) return <div className="min-h-[100dvh] bg-[hsl(var(--background))] px-5 py-16"><div className="mx-auto max-w-xl"><DashboardState title="Your workspace is resting." text="We could not load your private information right now. Please try again without refreshing your account." action={<button type="button" onClick={() => { void profileQuery.refetch(); void appointmentsQuery.refetch(); }} className="focus-ring rounded-full bg-[hsl(var(--primary))] px-5 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]" data-testid="button-dashboard-retry">Try again</button>} /></div></div>;
  const profile = profileQuery.data;
  const appointments = appointmentsQuery.data ?? [];
  return <div className="grain min-h-[100dvh] bg-[hsl(var(--background))]">
    <header className="border-b border-[hsl(var(--border)/.75)] bg-[hsl(var(--background)/.9)]"><div className="page-wrap flex h-[76px] items-center justify-between gap-4"><Link href="/" className="focus-ring flex items-center gap-3" data-testid="link-dashboard-logo"><span className="grid size-10 place-items-center rounded-[14px] bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"><UserRound size={19} /></span><span><span className="serif block text-lg font-semibold text-[hsl(var(--foreground))]">Your private space</span><span className="block text-[9px] font-bold uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))]">Client workspace</span></span></Link><div className="flex items-center gap-2"><Link href="/book" className="focus-ring hidden rounded-full bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))] sm:inline-flex" data-testid="link-dashboard-book">Request a session</Link><button type="button" onClick={() => { queryClient.clear(); void signOut(); }} className="focus-ring inline-flex items-center gap-2 rounded-full border border-[hsl(var(--border))] px-3 py-2.5 text-xs font-bold text-[hsl(var(--muted-foreground))]" data-testid="button-dashboard-sign-out"><LogOut size={14} /><span className="hidden sm:inline">Sign out</span></button></div></div></header>
    <main className="page-wrap py-10 md:py-16"><div className="animate-rise-in"><p className="eyebrow">Welcome back</p><h1 className="section-title mt-3 text-[hsl(var(--primary))]">{profile?.preferredName || profile?.fullName || user?.firstName || 'Your space'}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[hsl(var(--muted-foreground))]">A quiet place to review the details you have shared and keep track of appointment requests.</p></div>
      <section className="mt-10 grid gap-4 md:grid-cols-[1.1fr_.9fr]"><div className="rounded-[26px] bg-[hsl(var(--primary))] p-7 text-[hsl(var(--primary-foreground))]"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[hsl(var(--primary-foreground)/.12)]"><UserRound size={21} /></div><div><p className="eyebrow !text-[hsl(var(--accent))]">Profile summary</p><p className="mt-1 text-sm text-[hsl(var(--primary-foreground)/.7)]">Only you and the practice can see this.</p></div></div><div className="mt-7 grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-[hsl(var(--primary-foreground)/.55)]">Preferred format</p><p className="mt-1 font-semibold">{profile?.preferredFormat || 'Not specified'}</p></div><div><p className="text-xs text-[hsl(var(--primary-foreground)/.55)]">Preferred language</p><p className="mt-1 font-semibold">{profile?.preferredLanguage || 'Not specified'}</p></div><div><p className="text-xs text-[hsl(var(--primary-foreground)/.55)]">Contact preference</p><p className="mt-1 font-semibold">{profile?.preferredContactMethod || 'Not specified'}</p></div><div><p className="text-xs text-[hsl(var(--primary-foreground)/.55)]">Profile status</p><p className="mt-1 inline-flex items-center gap-1.5 font-semibold"><span className="size-2 rounded-full bg-[hsl(var(--accent))]" /> Complete</p></div></div><Link href="/book" className="focus-ring mt-7 inline-flex items-center rounded-full bg-[hsl(var(--accent))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--accent-foreground))]" data-testid="link-dashboard-profile-book">Choose a first step</Link></div><div className="rounded-[26px] border border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.55)] p-7"><p className="eyebrow">A gentle reminder</p><p className="serif mt-4 text-2xl text-[hsl(var(--primary))]">You can take your time here.</p><p className="mt-4 text-sm leading-7 text-[hsl(var(--muted-foreground))]">An appointment request is not a commitment. The practice will reply with next steps.</p><div className="mt-7 flex items-center gap-2 text-xs font-bold text-[hsl(var(--primary))]"><Clock3 size={16} /> Requests are reviewed privately</div></div></section>
      <section className="mt-12" data-testid="dashboard-appointments"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">Your requests</p><h2 className="serif mt-2 text-3xl text-[hsl(var(--primary))]">Appointments</h2></div><Link href="/book" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-dashboard-new-request"><CalendarDays size={16} /> New request</Link></div>{appointments.length === 0 ? <div className="mt-6 rounded-[24px] border border-dashed border-[hsl(var(--border))] p-8 text-center"><CalendarDays className="mx-auto text-[hsl(var(--accent-foreground))]" size={25} /><p className="serif mt-4 text-xl text-[hsl(var(--primary))]">Nothing requested yet.</p><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">When you are ready, a small request is enough to begin.</p></div> : <div className="mt-6 space-y-3">{appointments.map((appointment) => <article key={appointment.id} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card)/.65)] p-5" data-testid={`card-dashboard-appointment-${appointment.id}`}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="font-bold text-[hsl(var(--primary))]">{appointment.serviceName}</p><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{appointment.preferredDate.slice(0, 10)} · {appointment.preferredTime}</p></div><span className={`inline-flex w-fit rounded-full px-3 py-1.5 text-xs font-bold ${appointment.status === 'confirmed' ? 'bg-[hsl(var(--accent)/.2)] text-[hsl(var(--accent-foreground))]' : appointment.status === 'rejected' ? 'bg-[hsl(var(--destructive)/.1)] text-[hsl(var(--destructive))]' : 'bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]'}`} data-testid={`status-appointment-${appointment.id}`}>{appointment.status === 'pending' ? 'Awaiting reply' : appointment.status}</span></div>{appointment.message && <p className="mt-4 border-t border-[hsl(var(--border))] pt-4 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{appointment.message}</p>}</article>)}</div>}</section>
    </main>
  </div>;
}