import { useEffect } from 'react';
import { useAuth, useClerk, useUser } from '@clerk/react';
import { CheckCircle2, CircleAlert, Clock3, LogOut, ShieldCheck, XCircle } from 'lucide-react';
import { getGetMyProfileQueryKey, useGetMyProfile } from '@workspace/api-client-react';
import { Link, useLocation } from 'wouter';

function StaffStatus({ status }: { status: 'pending' | 'verified' | 'rejected' }) {
  const config = status === 'verified' ? { icon: CheckCircle2, title: 'Verified access', text: 'Your practice role has been verified server-side.', className: 'bg-[hsl(var(--accent)/.14)] text-[hsl(var(--accent-foreground))]' } : status === 'rejected' ? { icon: XCircle, title: 'Request not approved', text: 'Please contact the practice if you believe this needs another review.', className: 'bg-[hsl(var(--destructive)/.1)] text-[hsl(var(--destructive))]' } : { icon: Clock3, title: 'Verification in progress', text: 'Your request is waiting for a private practice review.', className: 'bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]' };
  const Icon = config.icon;
  return <div className={`rounded-[24px] p-6 ${config.className}`} data-testid={`status-staff-${status}`}><Icon size={25} /><p className="mt-4 font-bold">{config.title}</p><p className="mt-2 text-sm leading-6 opacity-80">{config.text}</p></div>;
}

export default function Staff() {
  const { isLoaded, isSignedIn } = useAuth();
  const { user } = useUser();
  const { signOut } = useClerk();
  const [, setLocation] = useLocation();
  const profileQuery = useGetMyProfile({ query: { enabled: isLoaded && !!isSignedIn, queryKey: getGetMyProfileQueryKey() } });
  useEffect(() => {
    if (isLoaded && !isSignedIn) setLocation('/sign-in?redirect_url=/staff');
  }, [isLoaded, isSignedIn, setLocation]);
  if (!isLoaded || profileQuery.isLoading) return <div className="grid min-h-[100dvh] place-items-center bg-[hsl(var(--background))]"><div className="h-28 w-full max-w-xl animate-pulse rounded-[28px] bg-[hsl(var(--muted))]" /></div>;
  if (!isSignedIn) return null;
  if (profileQuery.error) return <div className="grid min-h-[100dvh] place-items-center bg-[hsl(var(--background))] px-5"><div className="max-w-xl rounded-[28px] border border-[hsl(var(--border))] p-8 text-center"><CircleAlert className="mx-auto text-[hsl(var(--destructive))]" /><h1 className="serif mt-4 text-2xl text-[hsl(var(--primary))]">Workspace unavailable</h1><p className="mt-3 text-sm leading-7 text-[hsl(var(--muted-foreground))]">We could not confirm your account access. Please try again shortly.</p><button type="button" onClick={() => void profileQuery.refetch()} className="focus-ring mt-5 rounded-full bg-[hsl(var(--primary))] px-5 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]" data-testid="button-staff-retry">Try again</button></div></div>;
  const profile = profileQuery.data;
  const status = profile?.verificationStatus ?? 'pending';
  const hasStaffRole = profile?.role === 'staff' || profile?.role === 'admin';
  const hasPrivilegedRequest = profile?.accountType === 'staff' || profile?.accountType === 'admin';
  if (!hasStaffRole && !hasPrivilegedRequest) return <div className="min-h-[100dvh] bg-[hsl(var(--background))] px-5 py-16"><div className="mx-auto max-w-xl rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-8 text-center" data-testid="staff-access-denied"><ShieldCheck className="mx-auto text-[hsl(var(--primary))]" size={28} /><h1 className="serif mt-5 text-3xl text-[hsl(var(--primary))]">This is a staff-only space.</h1><p className="mt-3 text-sm leading-7 text-[hsl(var(--muted-foreground))]">Your client workspace remains available. If you work with the practice, you can request verification from onboarding.</p><Link href="/dashboard" className="focus-ring mt-6 inline-flex rounded-full border border-[hsl(var(--primary)/.3)] px-5 py-3 text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-staff-denied-dashboard">Go to client workspace</Link></div></div>;
  return <div className="grain min-h-[100dvh] bg-[hsl(var(--background))]"><header className="border-b border-[hsl(var(--border)/.75)] bg-[hsl(var(--background)/.9)]"><div className="page-wrap flex h-[76px] items-center justify-between gap-4"><Link href="/" className="focus-ring flex items-center gap-3" data-testid="link-staff-logo"><span className="grid size-10 place-items-center rounded-[14px] bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"><ShieldCheck size={19} /></span><span><span className="serif block text-lg font-semibold text-[hsl(var(--foreground))]">Practice workspace</span><span className="block text-[9px] font-bold uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))]">Private access</span></span></Link><button type="button" onClick={() => void signOut()} className="focus-ring inline-flex items-center gap-2 rounded-full border border-[hsl(var(--border))] px-3 py-2.5 text-xs font-bold text-[hsl(var(--muted-foreground))]" data-testid="button-staff-sign-out"><LogOut size={14} /> <span className="hidden sm:inline">Sign out</span></button></div></header><main className="page-wrap py-12 md:py-20"><p className="eyebrow">Hello {profile?.preferredName || profile?.fullName || user?.firstName || 'there'}</p><h1 className="section-title mt-3 text-[hsl(var(--primary))]">A considered place to do the work.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[hsl(var(--muted-foreground))]">Your role and verification status are controlled by the practice. This page never grants access based on a self-selected role.</p><div className="mt-10 grid gap-4 md:grid-cols-[.8fr_1.2fr]"><StaffStatus status={status} /><div className="rounded-[24px] bg-[hsl(var(--primary))] p-7 text-[hsl(var(--primary-foreground))]"><p className="eyebrow !text-[hsl(var(--accent))]">Access boundary</p><h2 className="serif mt-3 text-2xl">Privacy is part of the practice.</h2><p className="mt-4 text-sm leading-7 text-[hsl(var(--primary-foreground)/.7)]">{status === 'verified' && hasStaffRole ? 'You can use this verified workspace for practice work. Keep client information within approved systems and follow the practice’s confidentiality procedures.' : status === 'verified' ? 'Your professional request has been reviewed, but this account still does not have privileged access. Practice administration remains separately protected.' : 'Until the practice completes its review, no privileged staff or administrator tools are available to this account.'}</p>{status === 'verified' && profile?.role === 'admin' && <Link href="/admin" className="focus-ring mt-7 inline-flex rounded-full bg-[hsl(var(--accent))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--accent-foreground))]" data-testid="link-staff-admin">Open practice administration</Link>}</div></div></main></div>;
}